### ISSUE TITLE
运行客户端命令遇错

### ISSUE THREAD

**Issue by luckypoem** [changlan/kytan#30]
hi.

bogon:release brite$ sudo ~/kytan/target/release/kytan --mode c -h my-vps-ip -p 9527 --secret iloveson
会显示：
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Unspecified', src/libcore/result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
bogon:release brite$

怎么解决？

**Comment by briteming** [comment]
你好。
我在Mac上，编译了新版，不过，
yudeMacBook-Air:release ym$ sudo ./kytan client -s vps-public-ip -p 9527 -k mykey
Password:
add host vps-public-ip: gateway 192.168.1.1
delete net default
add net default: gateway 10.10.10.1
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 35, kind: WouldBlock, message: "Resource temporarily unavailable" }', src/network.rs:236:57
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
delete net default
add net default: gateway 192.168.1.1
delete host vps-public-ip
yudeMacBook-Air:release ym$

怎么解决这问题？
谢谢回复。
